services:
  app:
    build:
      context: ./docker/app
    init: true
    volumes:
      - ..:/workspaces/{{project_name}}:cached
    extra_hosts:
      - "mylocaldoma.in:host-gateway"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./docker/web
    ports:
      - "{{wordpress_port}}:80"
    volumes:
      - ..:/workspaces/{{project_name}}:cached
    depends_on:
      - app

  db:
    image: mysql:8.0
    ports:
      - "{{database_port}}:3306"
    environment:
      MYSQL_DATABASE: "{{database_name}}"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
